SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS ONLINE_SALE_ID, PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM ONLINE_SALE
WHERE DATE_FORMAT(SALES_DATE, '%Y-%m') LIKE '2022-03%'

UNION

SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS OFFLINE_SALE_ID, PRODUCT_ID, NULL, SALES_AMOUNT
FROM OFFLINE_SALE
WHERE DATE_FORMAT(SALES_DATE, '%Y-%m') LIKE '2022-03%'
ORDER BY 1,2,3