SELECT
    D.DR_NAME,
    D.DR_ID,
    D.MCDP_CD,
    DATE_FORMAT(D.HIRE_YMD, '%Y-%m-%d') as HIRE_YMD
FROM
    DOCTOR AS D
WHERE
    D.MCDP_CD LIKE 'CS' OR D.MCDP_CD LIKE 'GS'
GROUP BY
    D.DR_NAME
ORDER BY
    D.HIRE_YMD DESC, D.DR_NAME